# Use official Node.js image as the base image
FROM node:alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY Server/package*.json ./

# Install dependencies
RUN npm ci

# Copy the application files
COPY Server/ .

# Expose port 3000 (or any other port your Node.js app is using)
EXPOSE 3000

# Command to start the Node.js/Express app
CMD ["node", "main.js"]
